### PR TITLE
cmix v15 results

### PR DESCRIPTION
**Pull request by byronknoll**

### CODE REVIEW

**Comment by tarsa** [comment]
Thanks for the results. Do you have results for previous versions of cmix at hand? I'm interested in them, but on your page I see only results for newest version. Rerunning cmix for e.g. Silesia corpus could potentially take a long time.

Results for old versions could be marked as outdated in the CSVs, so they would not be displayed by default at all.

**Comment by byronknoll** [comment]
I do have historical results for cmix for most of these benchmarks. However, it would currently be very tedious to include all of those results (for various reasons). I made some feature requests on encode.ru that might make it less tedious to include historical results.

**Comment by tarsa** [comment]
Hi Byron,
I've addressed most of your requests. Two biggest items on current TODO list are:
- usage and contribution guide
- handling of individual compression options per each file - for that I'll perhaps add additional column to CSV data which will contain a comment explaining the options

but they shouldn't affect typical contributions a lot.

**Comment by byronknoll** [comment]
Thanks, the changes look good.

To me the UI for outdated results is awkward. Having two separate tables for that is redundant. Showing outdated results is a binary state, so only one selection is necessary.

**Comment by tarsa** [comment]
I think these tables will be useful to me in the future. Anyway, I'll add "select all" and "unselect all" buttons for convenience.

**Comment by tarsa** [comment]
Buttons added

**Pull request merged**
